use_frameworks!
platform :ios,'11.0'

target 'AwesomeBadge_Example' do
  pod 'AwesomeBadge', :path => '../'

  target 'AwesomeBadge_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
    pod 'FontAwesome.swift'
  end
end
